create table cliente (
	cod_cliente INT PRIMARY KEY,
	nome VARCHAR(50),
	sexo VARCHAR(50),
	dt_nascimento DATE,
	bairro VARCHAR(23)
);
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (1, 'Eva Millam', 'F', '1972/11/10', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (2, 'Beauregard Bachelor', 'M', '1948/09/30', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (3, 'Siusan Morison', 'F', '1974/11/03', 'Beira Mar');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (4, 'Vivianna Waddingham', 'F', '1977/03/09', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (5, 'Nicolle Akrigg', 'F', '1965/01/21', 'Bar do Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (6, 'Brannon Whicher', 'M', '1958/06/28', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (7, 'Selia Snelle', 'F', '1988/05/17', 'Paulicéia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (8, 'Gav Brun', 'M', '1965/03/07', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (9, 'Lilith Frances', 'F', '1954/08/01', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (10, 'Hilda Bunting', 'F', '1969/08/02', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (11, 'Beryle Ferebee', 'F', '1991/01/24', 'Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (12, 'Jay Mathet', 'M', '1984/05/18', 'Beira Mar');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (13, 'Marlane Guidelli', 'F', '1969/10/22', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (14, 'Gerek Hirtzmann', 'M', '1948/08/20', 'Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (15, 'Sampson Van den Velden', 'M', '1960/03/25', 'Bar do Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (16, 'Wyn Southby', 'M', '1991/12/21', 'Beira Mar');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (17, 'Toby Dimic', 'F', '1988/10/27', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (18, 'Terencio Coldrick', 'M', '1986/06/11', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (19, 'Wynne Norbury', 'F', '1995/09/25', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (20, 'Wilden Thomke', 'M', '1963/09/20', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (21, 'Wilfrid Shovelton', 'M', '1954/05/18', 'Beira Mar');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (22, 'Sarine Godin', 'F', '1981/10/14', 'Vila São Luis');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (23, 'Vin Klein', 'F', '1978/01/18', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (24, 'Huberto Allone', 'M', '1973/10/14', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (25, 'Vidovik Faltin', 'M', '1975/07/22', 'Paulicéia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (26, 'Richmound Booler', 'M', '1944/05/28', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (27, 'Jodie Giorio', 'F', '1997/10/18', 'Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (28, 'Uriah Crocroft', 'M', '1970/02/26', 'Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (29, 'Remington Tosh', 'M', '1965/12/14', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (30, 'Hill McLarens', 'M', '1960/04/01', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (31, 'Mae Benmore', 'F', '2007/01/20', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (32, 'Zorah Coch', 'F', '1949/06/18', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (33, 'Flossy Templman', 'F', '2007/07/09', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (34, 'Em Oldis', 'F', '1992/01/06', 'Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (35, 'Berne Auld', 'M', '1976/01/01', 'Vila São Luis');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (36, 'Allistir Kisar', 'M', '1959/01/20', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (37, 'Moe Pavia', 'M', '1956/11/05', 'Vila São Luis');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (38, 'Brit Spavon', 'M', '2009/06/05', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (39, 'Ric Pendall', 'M', '2004/05/16', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (40, 'Robin Loalday', 'F', '1955/03/04', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (41, 'Nata Ivanikhin', 'F', '1970/02/22', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (42, 'Javier Richardot', 'M', '1944/05/26', 'Bar do Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (43, 'Jerrome Mew', 'M', '1983/07/06', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (44, 'Vi Cristou', 'F', '1983/07/26', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (45, 'Benedict Barczynski', 'M', '1993/10/07', 'Paulicéia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (46, 'Sheelah Gercken', 'F', '1953/10/22', 'Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (47, 'Bobby Trevains', 'M', '1999/08/30', 'Paulicéia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (48, 'Godart Jedrzejewicz', 'M', '1947/10/22', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (49, 'Mord Maw', 'M', '1964/07/13', 'Bar do Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (50, 'Marcel Uglow', 'M', '1970/08/13', 'Beira Mar');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (51, 'Melina Parkman', 'F', '2008/07/11', 'Bar do Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (52, 'Gayel Hammerstone', 'F', '1940/09/24', 'Beira Mar');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (53, 'Zared Huntley', 'M', '1993/10/04', 'Vila São Luis');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (54, 'Myrna MacCartair', 'F', '1993/06/30', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (55, 'Emmey Harden', 'F', '2009/02/14', 'Bar do Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (56, 'Caleb Devonshire', 'M', '1965/09/17', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (57, 'Charlotte Gleave', 'F', '1946/08/04', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (58, 'Leonelle Ottey', 'F', '2010/08/20', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (59, 'Ambrosio Haynes', 'M', '1975/12/08', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (60, 'Angela Roden', 'F', '2007/05/02', 'Bar do Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (61, 'Rustie Kares', 'M', '1968/05/09', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (62, 'Haley Gergus', 'M', '1974/04/23', 'Paulicéia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (63, 'Manuel Del Castello', 'M', '1944/03/24', 'Vinte e Cinco de Agosto');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (64, 'Anallese Paterson', 'F', '1993/03/17', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (65, 'Borden Cinderey', 'M', '1973/02/18', 'Parque Senhor do Bonfim');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (66, 'Jeremie Casado', 'M', '1966/09/30', 'Parque Senhor do Bonfim');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (67, 'Claire Lehr', 'M', '1987/01/03', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (68, 'Lorette Saines', 'F', '1941/04/05', 'Parque Senhor do Bonfim');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (69, 'Adorne Muffitt', 'F', '1957/04/22', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (70, 'Blondell Cicculini', 'F', '2007/11/01', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (71, 'Friedrick Kirke', 'M', '1952/12/08', 'Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (72, 'Niven Kinmond', 'M', '1987/11/27', 'Centro');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (73, 'Hillel Badham', 'M', '1979/02/19', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (74, 'Alvis Bygrave', 'M', '1978/02/05', 'Beira Mar');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (75, 'Hamilton Rego', 'M', '1974/04/20', 'Parque Senhor do Bonfim');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (76, 'Karalee Heinschke', 'F', '2006/03/01', 'Gramacho');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (77, 'Olivette Wingate', 'F', '1996/01/30', 'Vila São Luis');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (78, 'Meredith Ruppert', 'M', '1997/11/24', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (79, 'Dru Ackenhead', 'M', '1995/05/15', 'Vila São Luis');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (80, 'Ulrika Bruhnke', 'F', '1998/04/21', 'Vila São Luis');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (81, 'Reagan Littleproud', 'M', '2004/05/10', 'Bar do Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (82, 'Gretna Lubeck', 'F', '1976/06/01', 'Beira Mar');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (83, 'Frannie Warrior', 'F', '1951/11/17', 'Paulicéia');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (84, 'Lenee Verheijden', 'F', '1943/10/15', 'Bar do Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (85, 'Chandler Senten', 'M', '1956/02/09', 'Bar do Cavaleiros');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (86, 'Simmonds Giacubo', 'M', '2000/12/06', 'Vila Operária');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (87, 'Evelin Dallender', 'M', '1989/03/21', 'Centenário');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (88, 'Dom Carlet', 'M', '1952/01/19', 'Parque Lafaiete');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (89, 'Nichol Ledster', 'F', '1967/04/03', 'Parque Senhor do Bonfim');
insert into cliente (cod_cliente, nome, sexo, dt_nascimento, bairro) values (90, 'Juline Saill', 'F', '1951/11/27', 'Vinte e Cinco de Agosto');
